helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    version: 0.14.9
    releaseName: metallb
    namespace: metallb-system
resources:
  - l2-advertisement.yaml
  - ip-address-pool.yaml
