helmCharts:
  - name: mimir-distributed
    repo: https://grafana.github.io/helm-charts
    version: 5.7.0
    releaseName: mimir
    namespace: mimir
    valuesInline:
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
        hosts:
          - mimir.koyashiro.net
