helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    version: 8.0.9
    releaseName: argo-cd
    namespace: argocd
    valuesInline:
      global:
        domain: argocd.koyashiro.net
      configs:
        cm:
          kustomize.buildOptions: --enable-helm
      server:
        ingress:
          enabled: true
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
            nginx.ingress.kubernetes.io/ssl-passthrough: "true"
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          ingressClassName: nginx
          hostname: argocd.koyashiro.net
          tls: true
