apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/koyashiro/k8s-manifests
      targetRevision: HEAD
      path: kustomizations/argocd
      valuesObject:
        global:
          domain: argocd.koyashiro.net
        configs:
          cm:
            kustomize.buildOptions: --enable-helm
        server:
          ingress:
            enabled: true
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt
              nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            ingressClassName: nginx
            hostname: argocd.koyashiro.net
            tls: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
