apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  sources:
    - chart: argo-cd
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: v8.0.9
      helm:
        valuesObject:
          global:
            domain: argocd.koyashiro.net
          server:
            ingress:
              enabled: true
              annotations:
                cert-manager.io/cluster-issuer: letsencrypt
                nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: HTTPS
              ingressClassName: nginx
              hostname: argocd.koyashiro.net
              tls: true
    - repoURL: https://github.com/koyashiro/k8s-manifests
      targetRevision: HEAD
      path: applications/argocd
      directory:
        exclude: application.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
