helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    version: 1.8.1
    releaseName: longhorn
    namespace: longhorn-system
    valuesInline:
      preUpgradeChecker:
        jobEnabled: false
      defaultSettings:
        allowCollectingLonghornUsageMetrics: false
      ingress:
        enabled: true
        host: longhorn.koyashiro.net
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/backend-protocol: HTTP
          nginx.ingress.kubernetes.io/auth-type: basic
          nginx.ingress.kubernetes.io/auth-secret: longhorn-basic-auth
          nginx.ingress.kubernetes.io/auth-realm: Authentication Required
        tls: true
        tlsSecret: longhorn-tls
