apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - chart: longhorn
      repoURL: https://charts.longhorn.io/
      targetRevision: v1.8.1
      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          ingress:
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-issuer
            enabled: true
            host: longhorn.koyashiro.net
            ingressClassName: nginx
          tls: true
          tlsSecret: longhorn-tls-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
