apiVersion: v1
kind: Secret
metadata:
  name: longhorn-basic-auth
  namespace: longhorn-system
  annotations:
    argocd.argoproj.io/sync-options: Skip
type: Opaque
stringData:
  auth: "" # replace this later
